services:
  - type: web
    name: hotel-management-backend
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: PROJECT_ID
        value: hotel-management-system
      - key: CORS_ORIGIN
        value: "*"
      - key: FRONTEND_URL
        value: "https://your-frontend-domain.com"
